test: optimise test with chai custom method overwrite
AwesomeHamster/lodestone-news pull request #22
Opened 2022-08-31 06:32 UTC by MaikoTan

2022-09-01 07:27 UTC, SaarChaffee requested changes

2022-09-01 07:27 UTC, SaarChaffee commented on __tests__/index.spec.ts
> +Assertion.overwriteChainableMethod('an', a, noop)
```suggestion
import { Assertion, expect, util } from 'chai'

import { defaultRules, getNews, LodestoneNews, regions, News } from '../src'

const UTC_0_2022_07_19_07_59_59 = 1658217599 * 1000 // 2022-07-19 07:59:59 UTC+0

Assertion.addProperty('newsList', function () {
  new Assertion(this._obj).to.be.instanceof(Array<News>)
  this._obj.forEach(n => {
    new Assertion(n).to.have.deep.property('title').which.is.a('string')
    new Assertion(n).to.have.deep.property('epoch').which.is.a('number')
    new Assertion(n).to.have.deep.property('url').which.is.a('string')
    new Assertion(n).to.have.deep.property('date').which.is.a('date')
  })
  this.assert(
    this._obj instanceof Array<News>,
    'expected #{this} to be an array of News',
    'expected #{this} to not be an array of News',
    null,
  )
})

Assertion.addMethod('haveLen', function (n?: number) {
  if (util.flag(this, 'newsList')) {
    new Assertion(this._obj).to.have.deep.property('length').which.is.a('number')
    if (n) {
      new Assertion(this._obj).to.have.lengthOf(n)
      this.assert(
        this._obj.length === n,
        'expected #{this} to have #{exp} news, but got #{act}',
        'expected #{this} to not have #{exp} news, but got #{act}',
        n,
        this._obj.length,
      )
    } else {
      new Assertion(this._obj).to.have.lengthOf.greaterThan(0)
      this.assert(
        this._obj.length > 0,
        'expected #{this} to have more than one news, but got #{exp}',
        'expected #{this} to not have more than one news, but got #{exp}',
        this._obj.length,
      )
    }
  }
})
```

2022-09-01 07:27 UTC, SaarChaffee commented on __tests__/index.spec.ts
> +        expect(news[0]).is.a('news')
现在可以这么用，`haveLen()` 入参为空则判断大于0
```suggestion
        expect(news).is.a.newsList.that.haveLen()
```

2022-09-01 07:27 UTC, SaarChaffee commented on __tests__/index.spec.ts
> +  expect(news[0]).is.a('news')
```suggestion
  expect(news).is.a.newsList.that.haveLen()
```

2022-09-01 07:27 UTC, SaarChaffee commented on __tests__/index.spec.ts
> +  expect(news[0]).is.a('news')
```suggestion
  expect(news).is.a.newsList.that.haveLen(10)
```

2022-09-01 07:27 UTC, SaarChaffee commented on __tests__/index.spec.ts
> +  expect(news).has.length(2)
```suggestion
  expect(news).is.a.newsList.that.haveLen(2)
```

2022-09-01 10:39 UTC, SaarChaffee requested changes

2022-09-01 10:39 UTC, SaarChaffee commented on __tests__/index.spec.ts
>  })
```suggestion
  util.flag(this, 'newsList', true)
})
```

2022-09-01 10:41 UTC, SaarChaffee requested changes

2022-09-01 10:41 UTC, SaarChaffee commented on __tests__/index.spec.ts
> +      }
```suggestion
      }
      util.flag(this, 'newsList', false)
```

2022-09-02 02:40 UTC, SaarChaffee approved these changes

2022-09-02 06:12 UTC, MaikoTan commented
[The lodestone is maintaining currently](https://jp.finalfantasyxiv.com/lodestone/news/detail/5bcbc0d889444667265d97d324205537b508973b), which broke the test always.

2022-09-02 08:34 UTC, SaarChaffee commented
```log
 29 passing (3m)
 1 failing
```

2022-09-02 10:47 UTC, MaikoTan commented
you can trigger the ci test by clicking the re-run button.

2022-09-02 11:23 UTC, SaarChaffee requested changes

2022-09-02 11:23 UTC, SaarChaffee commented on __tests__/index.spec.ts
> +  expect(news).to.be.newsList.which.has.length(20)
```suggestion
  expect(news).to.be.newsList.which.has.length(10)
```

2022-09-02 13:57 UTC, SaarChaffee approved these changes

2022-09-02 13:58 UTC, merged